### PR TITLE
(4) 2365 upload a document: Document table

### PR DESCRIPTION
**Pull request by maiyerlee**
## What changed

- Create a new SQLAlchemy base model for documents.
- Add a new migration script to update the database schema.

## Issue

[Upload a document #2365](https://github.com/HHS/OPRE-OPS/issues/2365)

## How to test
1. Start and update the database using the changes: `docker compose up db data-import --build`
2. There should be a `document` table with the following columns:
Screenshot 2024-07-17 at 5 32 17 PM

3. There should be a new data type called 'documenttype' with the following enum values: 
`[CERTIFICATION_OF_FUNDING, STATEMENT_OF_REQUIREMENTS, ITAR_CHECKLIST_FOR_ALL_IT_PROCUREMENT_ACTIONS, INDEPENDENT_GOVERNMENT_COST_ESTIMATE, SECTION_508_EXCEPTION_DOCUMENTATION, COR_NOMINATION_AND_CERTIFICATION_DOCUMENT, ADDITIONAL_DOCUMENT]`

## Definition of Done Checklist
- [x] OESA: Code refactored for clarity
- [x] OESA: Dependency rules followed
- [x] Automated unit tests updated and passed
- [x] Automated integration tests updated and passed
- [x] Automated quality tests updated and passed
- [x] Automated load tests updated and passed
- [x] Automated a11y tests updated and passed
- [x] Automated security tests updated and passed
- [ ] 90%+ Code coverage achieved
- [ ] Form validations updated

## Links

Links to prior PRs:
1. https://github.com/HHS/OPRE-OPS/pull/2406
2. https://github.com/HHS/OPRE-OPS/pull/2523
3. https://github.com/HHS/OPRE-OPS/pull/2539 
4. https://github.com/HHS/OPRE-OPS/pull/2553

### CODE REVIEW

**Review by johndeange — APPROVED** [review]

**Review by fpigeonjr — APPROVED** [review]
image

**Comment by fpigeonjr** [comment]
🧡 must say this is a well-formatted PR. Love the links to prev PRs. May copy this for my future PRs.

**Comment by maiyerlee** [comment]
Missing in the original changeset: 
- status and document_id attributes to the document model
- proper importing
- version table

Updates produce the following tables: 
Screenshot 2024-07-22 at 7 53 33 AM
Screenshot 2024-07-22 at 7 53 55 AM

**Comment by maiyerlee** [comment]
I created a migration merge script to resolve the Alembic error `FAILED: Multiple head revisions are present for given argument 'head'; please specify a specific target revision, '<branchname>@head' to narrow to a specific head, or 'heads' for all heads`.

Script = backend/alembic/versions/2024_07_22_1246-479d7630e94c_merge_f8ef3a3d90d7_and_a4a04f1f868e.py

**Review by stevtek — APPROVED** [review]

**Review by rajohnson90 — APPROVED** [review]

**Pull request merged**
