### PR TITLE
Ops 490 frontend

### PR DESCRIPTION
**Pull request by fpigeonjr**
## What changed

Research Projects front end

## Issue

# 490 and 497

## How to test

Visit the **Projects and Spending Tab** on a portfolio.

## Screenshots

SCR-20230303-e2b

### CODE REVIEW

**Comment by jonnalley** [comment]
🎉🎉🎉

**Review by johndeange — DISMISSED** [review]
Really good work!

- Please resolve the linting errors showing up in Github
- We will need to make a mental note to resolve the skipped unit tests at some point - there is some growing tech debt there

**Comment by fpigeonjr** [comment]
> Really good work!
> 
> * Please resolve the linting errors showing up in Github
> * We will need to make a mental note to resolve the skipped unit tests at some point - there is some growing tech debt there

Will  do @johndeange , thanks for the feedback.

**Comment by fpigeonjr** [comment]
> * Please resolve the linting errors showing up in Github
Linting errors have been fixed @johndeange. Thanks!

**Review by tdonaworth — APPROVED** [review]

**Pull request merged**
