### PR TITLE
Ops 2861/upgrade downgrade schema

### PR DESCRIPTION
**Pull request by johndeange**
## What changed

- Add scripts to upgrade/downgrade the DB schema
- Update the stg/prod deployments to run the DB schema update at deployment time

## Issue

https://github.com/HHS/OPRE-OPS/issues/2861

## How to test

After the workflows are merged to main, test the stg and prod deployments.

## Definition of Done Checklist
- [x] OESA: Code refactored for clarity
- [x] OESA: Dependency rules followed
- [x] Automated unit tests updated and passed
- [x] Automated integration tests updated and passed
- [x] Automated quality tests updated and passed
- [x] Automated load tests updated and passed
- [x] Automated a11y tests updated and passed
- [x] Automated security tests updated and passed
- [x] 90%+ Code coverage achieved
- [x] Form validations updated

### CODE REVIEW

**Comment by jonnalley** [comment]
So dev will still drop and re-create everything?

**Review by jonnalley — COMMENTED** [review]
LGTM :shipit: 🚀 💰

**Comment by johndeange** [comment]
> So dev will still drop and re-create everything?

Yes, that is the intent.  Also, I would eventually like to trigger the deploy on a new release rather than a merge to main.

**Review by fpigeonjr — APPROVED** [review]
💰

**Review by rajohnson90 — APPROVED** [review]

**Pull request merged**
